greenbone/pontos

- CHANGELOG.md
- README.md
Not absolutely sure about the "function for maintained", maybe there is also a word missing after "for"?
> Fix typos.

- pontos/release/release.py
Allow to use a different key for the release commits and tag then for
the signatures. The git signing key should match the committers gpg key
and the signing key should be a generic key.
**Checklist**:
> Add new option --git-signing-key

- pontos/release/release.py
> change not use next version to set it to as version in project

- pontos/release/release.py
- tests/release/test_release.py
> add second commit for changelog.md

- pontos/changelog/__init__.py
- pontos/changelog/changelog.py
- pontos/release/__init__.py
- pontos/release/release.py
- tests/changelog/test_changelog_update.py
> set changelog of tag without keep a changelog template, set new version

- pontos/changelog/changelog.py
- tests/changelog/test_changelog_changelog.py
- tests/changelog/test_changelog_update.py
on a release if there is a changelog with empty entries the empty
entries will be omitted.
**Checklist**:
> remove empty changelog entries

- pontos/changelog/changelog.py
- tests/changelog/test_changelog_update.py
> fix case when there is only a unreleased statement in CHANGELOG.md

- pontos/release/release.py
> Fix various typos.

- pontos/release/release.py
Display errors from running git.
**Checklist**:
> Print error output if a subcommand fails

- pontos/release/release.py
> add abort condition on empty updated text

- pontos/changelog/changelog.py
- tests/changelog/test_changelog_update.py
> Incorrect abort condition

- pontos/release/release.py
Display the default signing key id in help output.
**Checklist**:
> Update help output for signing key

- pontos/changelog/changelog.py
- tests/changelog/expected_changelog.md
- tests/changelog/expected_release_notes.md
- tests/changelog/test_changelog_update.py
- tests/changelog/unreleased_changelog_example.md
> add to changelog when there are changelog entries outside the loop

- tests/changelog/expected_changelog.md
- tests/changelog/expected_release_notes.md
- tests/changelog/unreleased_changelog_example.md
> add fixed entry for test

- CHANGELOG.md
- pontos/release/release.py
> add release name

- poetry.lock
- pontos/version/version.py
> Update pylint to version 2.6.0

- .github/dependabot.yml
**What**:
Fixing dependabot, allowing to push direct and indirect changes.
**Why**:
Dependabot did not update dependencies, yesterday.
**How**:
**Checklist**:
> Fixing dependabot

- CHANGELOG.md
- RELEASE.md
**What**:
* Change Versioning to Calendar Versioning
**Why**:
* Fit into Versioning Schema of our Projects
**How**:
**Checklist**:
> Prepare Release: Change Versioning to Calendar Versioning

- pontos/updateheader/updateheader.py
- tests/updateheader/test_header.py
**What**:
* Adding more tests to new feature
**Why**:
* Increase the coverage
**How**:
**Checklist**:
> Add additional tests for argparser

- .github/workflows/ci.yml
**What**:
Test and try GitHub Actions as CI
**Why**:
**How**:
**Checklist**:
> Add draft for a CI workflow with GitHub Actions

- .github/workflows/codeql-analysis.yml
**What**:
Start scanning the code via CodeQL for possible vulnerabilities
**Why**:
For now we scan for every PR to master and for every push(/merge) to master. Additionally a schedule on every Sunday at 5.30h is run to scan the code. In future it may be possible that we only run the schedule or deactivate it for PR because it cost 5minutes for every run at the moment.
**How**:
**Checklist**:
> Setting up code scanning

- .coveragerc
**What**:
Enable considering branches for coverage calculation
**Why**:
Background https://coverage.readthedocs.io/en/latest/branch.html#branch
**How**:
**Checklist**:
- n/a Tests
- n/a [CHANGELOG](https://github.com/greenbone/pontos/blob/master/CHANGELOG.md) Entry
- n/a Documentation
> Enable considering branches for coverage calculation

- .github/workflows/ci.yml
**What**:
**Why**:
**How**:
**Checklist**:
> Use new poetry github action

- .github/workflows/ci.yml
**What**:
It seems several actions can be put into one repo. Try out this new
action layout.
**Why**:
**How**:
**Checklist**:
> Use new actions

- pontos/release/release.py
**What**:
* Missing a `git push`
**Why**:
**How**:
**Checklist**:
> Fix update dev version after release

- .github/workflows/release-pontos.yml
**What**:
**Why**:
**How**:
**Checklist**:
> Adjust the script, tell git who I am

- .github/workflows/ci-python.yml
- .github/workflows/release-pontos.yml
**What**:
**Why**:
* PRs from forks don't pass secrets to workflows. :(
**How**:
**Checklist**:
> Try release from branch instead of fork

- .github/workflows/release-pontos.yml
**What**:
**Why**:
**How**:
**Checklist**:
> Try to release from branch instead of fork (2)

- .github/workflows/release-pontos.yml
**What**:
**Why**:
**How**:
**Checklist**:
> Try to release from branch instead of fork (3)

- CHANGELOG.md
- pontos/release/helper.py
- pontos/release/release.py
**What**:
**Why**:
**How**:
**Checklist**:
> Fixing commiting without signing

- pontos/release/helper.py
- tests/release/test_helper.py
Added tests.
**What**:
**Why**:
**How**:
**Checklist**:
> Check git config for signing key. Proceed without key, if missing.

- pontos/release/helper.py
- tests/release/test_release.py
**What**:
**Why**:
**How**:
**Checklist**:
> Signing: Also check for empty string

- pontos/release/release.py
**What**:
**Why**:
**How**:
**Checklist**:
> If no key available DONT sign

- .github/workflows/release-pontos.yml
**What**:
**Why**:
**How**:
**Checklist**:
> Add correct remote URL to release workflow

- .github/workflows/release-pontos.yml
**What**:
**Why**:
**How**:
**Checklist**:
> no persistent credentials

- CHANGELOG.md
- pontos/updateheader/templates/AGPL-3.0-or-later/template.xsl
- pontos/updateheader/templates/GPL-2.0-or-later/template.xsl
- pontos/updateheader/templates/GPL-3.0-or-later/template.xsl
- pontos/updateheader/updateheader.py
**What**:
This adds GPL-3.0-or-later, GPL-2.0-or-later and GPL-3.0-or-later
templates for .xsl files.
**Why**:
**How**:
**Checklist**:
> Add header templates for .xsl files

- CHANGELOG.md
- pontos/version/helper.py
**What**:
* If version has 'dev' version.dev == 0 so explicitly check for None is better here.
**Why**:
**How**:
**Checklist**:
> Check for dev-version correctly

- CHANGELOG.md
- pontos/release/release.py
- tests/release/test_release.py
**What**:
Adjust and improve the created git commit messages for and after a
release.
**Why**:
Get a cleaner git history for automatic releases with pontos.
**How**:
**Checklist**:
> Improve git commit messages

- pontos/release/helper.py
- pontos/release/release.py
**What**:
**Why**:
**How**:
**Checklist**:
> Small improvements

- CHANGELOG.md
- pontos/release/helper.py
- tests/release/test_release.py
**What**:
* Use --no-verify on git commit
**Why**:
* Avoid, that hooks interrupt pontos
**How**:
**Checklist**:
> Use --no-verify on git commit

- .github/workflows/release-pontos.yml
**What**:
**Why**:
**How**:
**Checklist**:
> Use correct secret name

- .github/workflows/release-pontos.yml
- CHANGELOG.md
- pontos/release/release.py
**What**:
**Why**:
**How**:
**Checklist**:
> Fix the Release Workflow CI

- .github/workflows/release-pontos.yml
**What**:
* In the workflow we need to enter the passphrase for the key we want to import.
* since we do not have a desktop we need to use the pinentrymode loopback and the passphrase argument
**Why**:
* importing (private) keys prompts for passphrase
**How**:
**Checklist**:
> [pontos-release] Use pinentry-mode also in import.

- .github/workflows/release-pontos.yml
- RELEASE.md
- changelog.toml
- pontos/changelog/__main__.py
- pontos/changelog/conventional_commits.py
- pontos/changelog/main.py
- pontos/release/__init__.py
- pontos/release/helper.py
- pontos/release/main.py
- pontos/release/prepare.py
- pontos/release/release.py
- pontos/release/sign.py
- pontos/terminal/terminal.py
- pyproject.toml
- tests/changelog/changelog.toml
- tests/changelog/test_changelog_update.py
- tests/changelog/test_conventional_commits.py
- tests/release/test_prepare.py
- tests/release/test_release.py
- tests/release/test_sign.py
- tests/release/v1.2.3.md
**What**:
* Implementing a tool to create conventional commits
* integrate it into the release process
**Why**:
* Switching to conventional commits [AP-1642]
**How**:
**Checklist**:
> Implement CHANGELOGs from conventional commits via git log

- .github/workflows/release-pontos.yml
- pontos/changelog/conventional_commits.py
**What**:
* Need to fetch deeper. 
**Why**:
AP-1642
**How**:
**Checklist**:
> Fetch deeper in checkout GitHub Action to release

- changelog.toml
- changelog/v21.9.0.md
- pontos/changelog/conventional_commits.py
- tests/changelog/changelog.toml
- tests/changelog/test_conventional_commits.py
**What**:
* Changed the regex in the channgelog.toml from past (added) to present (add)
* commits should use the present terms (Add: Blah), changelog will use the past (##Added ... * Blah)
* Fixed up the newlines in the generated changelog
**Why**:
**How**:
**Checklist**:
> Minor fixes for the Conventional Commits

- poetry.lock
- pyproject.toml
**What**:
**Why**:
**How**:
**Checklist**:
> Drop python 3.5, 3.6 support, add 3.9. Update dependencies

- .github/workflows/ci-python.yml
- .github/workflows/release-pontos-manually.yml
- .github/workflows/release-pontos.yml
**What**:
**Why**:
**How**:
**Checklist**:
> Update CI workflows to use new actions

- tests/fake_pyproject.toml
- tests/release/test_helper.py
- tests/updateheader/test_header.py
- tests/version/test_update_version_file.py
- tests/version/test_verify_version.py
**What**:
* Various tests failed
**Why**:
* Hardcoded month in the tests
**How**:
**Checklist**:
> Fixing the tests.

- pontos/git/__init__.py
- pontos/git/git.py
- tests/git/__init__.py
- tests/git/test_git.py
**What**:
Add a new module and class for providing an API for git.
**Why**:
Have an API for using git in python.
**How**:
**Checklist**:
> Add: New python module for git usage

- pontos/updateheader/updateheader.py
**What**:
**Why**:
**How**:
**Checklist**:
> Fix Argument parsing of update header

- .github/workflows/update-header.yml
- .pontos-header-ignore
**What**:
**Why**:
**How**:
**Checklist**:
> Add action for updating header at the start of the year

- pontos/updateheader/updateheader.py
**What**:
**Why**:
**How**:
**Checklist**:
> Fix: `pontos-update-header` Truncate file, so we do not left old file content.

- pontos/github/api.py
> Fixing MD Newlines by replace

- README.md
- pontos/github/api.py
- pontos/github/argparser.py
- pontos/github/cmds.py
**What**:
* add new command to add lables e.g.
`pontos-github labels greenbone/pontos 294 duplicate enhancement`
**Why**:
* Want to use for other repos.
**How**:
* Using GitHub API
**Checklist**:
> Add: API and cmd for adding labels to an Issue/PR

- pontos/terminal/terminal.py
- tests/terminal/test_terminal.py
**What**:
**Why**:
**How**:
**Checklist**:
> Fix: A problem, that occures, if `msg` contains newlines

- pontos/terminal/terminal.py
- tests/terminal/test_terminal.py
**What**:
* Newlines should be correcly formatted now
* The Symbol should be correctly placed in the first line now
**Why**:
**How**:
* Refactor the printing code
**Checklist**:
> Change: Do not replace `"\n"` with `" "`, but format the newlines correctly

- pontos/changelog/conventional_commits.py
- pontos/helper.py
- pontos/release/main.py
- pontos/release/prepare.py
- pontos/release/release.py
- pontos/release/sign.py
- tests/changelog/test_conventional_commits.py
- tests/release/test_prepare.py
- tests/release/test_release.py
- tests/release/test_sign.py
**What**:
**Why**:
**How**:
**Checklist**:
> Refactor: Exclude `shell_command_runner` from arguments

- pontos/github/api.py
- pontos/helper.py
- pontos/release/helper.py
- pontos/release/main.py
- pontos/release/sign.py
- tests/test_helper.py
**What**:
Split UI and business logic.
**Why**:
Better code layout and clear separation of concerns.
**How**:
**Checklist**:
> Download refactoring

- pontos/changelog/conventional_commits.py
- pontos/pontos.py
**What**:
**Why**:
**How**:
**Checklist**:
> Fix some typos

- tests/changelog/test_changelog_update.py
- tests/changelog/test_conventional_commits.py
- tests/github/test_argparser.py
- tests/release/test_prepare.py
- tests/release/test_release.py
- tests/release/test_sign.py
- tests/updateheader/test_header.py
- tests/version/test_cmake_version.py
- tests/version/test_go_version.py
- tests/version/test_version.py
**What**:
Avoid any output from tests to the console.
**Why**:
Get clean output for the test runner.
**How**:
**Checklist**:
> Tests cleanup

- poetry.lock
- pyproject.toml
**What**:
Improve required version specifications to allow a better range of
versions and only require direct dependencies.
**Why**:
Fixes #357
**How**:
**Checklist**:
> Change: Update dependencies to latest versions

- pontos/github/cmds.py
**What**:
Forward the terminal to the pr_func functions. These functions can be
create_pull_request and update_pull_request.
**Why**:
https://github.com/greenbone/vulnerability-tests/runs/7228160385?check_suite_focus=true
**How**:
**Checklist**:
> Fix: Fix creating and updating pull requests

- pontos/release/prepare.py
- pontos/version/__init__.py
- tests/release/test_prepare.py
**What**:
Use Git object for getting the list of available tags
**Why**:
Better code re-usage
**How**:
**Checklist**:
> Use Git object for getting the list of available tags

- pontos/github/api.py
- pontos/release/sign.py
- tests/github/test_api.py
**What**:
Improve uploading release assets
**Why**:
Allow to use a content type for asset uploads
**How**:
**Checklist**:
> Improve uploading release assets

- .github/workflows/github-pages.yml
**What**:
Add: Deploy docs to GitHub pages
**Why**:
Build and upload docs to GitHub pages. We will host the docs on GitHub pages for easy deployment via actions.
**How**:
**Checklist**:
> Add: Deploy docs to GitHub pages

- pontos/updateheader/templates/AGPL-3.0-or-later/template.py
- pontos/updateheader/templates/GPL-2.0-or-later/template.py
- pontos/updateheader/templates/GPL-3.0-or-later/template.py
- tests/updateheader/test_header.py
**What**:
Remove `# -*- coding: utf-8 -*-` from python templates
**Why**:
* Not required anymore.
**How**:
**Checklist**:
> Remove: utf-8 code comment in python header

- README.md
- docs/tools.rst
**What**:
Added noteblock in tools-doc & reference to doc in README.md
**Why**:
To improve pontos documentation
**How**:
Edit in texteditor
**Checklist**:
- [ x] Tests
- [ x] Conventional commit message
- [ x] Documentation
> Doc: Added note in tools-doc & reference to doc in README.md

- docs/conf.py
- docs/other.rst
**What**:
Some small improvements for the docs
* Link to Python 3 docs automatically
* Remove two doc build warnings
**Why**:
Get rid of some build warnings.
**How**:
**Checklist**:
> Small docs improvements

- pontos/github/api.py
- tests/github/test_api.py
**What**:
Implement [workflow](https://docs.github.com/en/rest/actions/workflows) and parts of [workflow-runs](https://docs.github.com/en/rest/actions/workflow-runs) API
DEVOPS-403
**Why**:
Required to trigger building artifacts
**How**:
**Checklist**:
> GitHub workflow API

- pontos/github/api.py
**What**:
Update json based types for GitHub API
**Why**:
The former JSON type was an json object. Therefore rename the type and introduce a new JSON type.
**How**:
**Checklist**:
> Change: Update json based types for GitHub API

- pontos/github/actions/env.py
- tests/github/actions/test_env.py
**What**:
Add GitHub Actions Environment property for is debug enabled
**Why**:
Allow to check if debug is enabled in the workflow run.
**How**:
**Checklist**:
> Add: Add GitHub Actions Environment property is_debug

- pontos/github/api/artifacts.py
**What**:
Add missing description of the artifact argument and fix example.
**Why**:
**How**:
**Checklist**:
> Fix: Update docstring of GitHub download_repository_artifact

- pontos/github/api/branch.py
**What**:
Fix mentioned call
**Why**:
`.json` is a function not attribute...
**How**:
**Checklist**:
> Fix: get_branch_protection API call

- pontos/github/api/helper.py
**What**:
Add WorkflowRunStatus enum for GitHub API
**Why**:
Allow to use an enum for GitHub workflow run status values.
**How**:
**Checklist**:
> Add: Add WorkflowRunStatus enum for GitHub API

- pontos/github/api/contents.py
- tests/github/api/test_contents.py
**What**:
path_exits -> path_exists
**Why**:
**How**:
**Checklist**:
> Fix: Type in function name

- tests/release/test_helper.py
- tests/version/test_javascript_version.py
**What**:
Improve release helper and JS update version tests
**Why**:
The release helper tests were flaky when they failed.
JS update version test did print its output to the console.
**How**:
**Checklist**:
- n/a Documentation
> Improve tests

- pontos/git/git.py
- pontos/github/api/release.py
- pontos/github/argparser.py
- pontos/github/cmds.py
- tests/git/test_git.py
- tests/github/api/test_release.py
- tests/github/test_argparser.py
- tests/github/test_cmds.py
**What**:
Add cmd option to create a github release to pontos-github.
Tested with privat token on privat repo.
**Why**:
**How**:
**Checklist**:
> Add: cmd option to create a github release to pontos-github

- pontos/github/api/__init__.py
- pontos/github/api/api.py
- pontos/github/api/artifacts.py
- pontos/github/api/branch.py
- pontos/github/api/client.py
- pontos/github/api/contents.py
- pontos/github/api/labels.py
- pontos/github/api/organizations.py
- pontos/github/api/pull_requests.py
- pontos/github/api/release.py
- pontos/github/api/workflows.py
- pontos/helper.py
- tests/__init__.py
- tests/github/api/__init__.py
- tests/github/api/test_artifacts.py
- tests/github/api/test_branch.py
- tests/github/api/test_client.py
- tests/github/api/test_contents.py
- tests/github/api/test_labels.py
- tests/github/api/test_organizations.py
- tests/github/api/test_pull_requests.py
- tests/github/api/test_release.py
- tests/github/api/test_workflows.py
- tests/test_helper.py
**What**:
Asynchronous GitHub API
**Why**:
Allow concurrent requests to the GitHub API
**How**:
**Checklist**:
> Async GitHub API

- pontos/github/api/api.py
- pontos/github/api/repositories.py
- tests/github/api/test_repositories.py
**What**:
Add an async GitHub API for handling repositories
**Why**:
We need to be able to create and change repositories.
**How**:
**Checklist**:
> Add: Add an async GitHub API for handling repositories

- docs/pontos/pontos.github.api.rst
- docs/pontos/pontos.github.rst
- docs/pontos/pontos.github.script.rst
- pontos/errors.py
- pontos/github/api/api.py
- pontos/github/api/helper.py
- pontos/github/script/__init__.py
- pontos/github/script/errors.py
- pontos/github/script/load.py
- pontos/github/script/parser.py
- pontos/helper.py
- pontos/testing/__init__.py
- pyproject.toml
- tests/github/script/__init__.py
- tests/github/script/test_load.py
- tests/github/script/test_parser.py
- tests/test_helper.py
- tests/testing/test_testing.py
**What**:
Add an API and CLI (`pontos-github-script`) to run scripts for GitHub automation.
DEVOPS-435
**Why**:
We need to automate different GitHub processes in future. This PR allows to write several scripts that run against the GitHub REST API.
**How**:
**Checklist**:
> Pontos GitHub script API

- .github/workflows/ci-python.yml
- .github/workflows/codeql-analysis-python.yml
- .github/workflows/deploy-pypi.yml
- .github/workflows/github-pages.yml
- .github/workflows/release-pontos-manually.yml
- .github/workflows/release-pontos.yml
- .github/workflows/update-header.yml
**What**:
* Run autoformatter on all workflow files
* Update our actions to v2 versions
**Why**:
Get rid of warnings in workflow runs
**How**:
**Checklist**:
> Change: Format workflows and update actions

- pontos/github/api/api.py
- pontos/github/api/organizations.py
- pontos/github/api/teams.py
- tests/github/api/test_teams.py
**What**:
Add async GitHub API for the teams API.
DEVOPS-435
**Why**:
We need to be able to automate teams.
**How**:
**Checklist**:
> Add teams API

- poetry.lock
- pontos/github/api/client.py
- pyproject.toml
**What**:
Use HTTP/2 if the server supports it for the async GitHub API.
**Why**:
Allow for even faster connections with async GitHub API.
**How**:
**Checklist**:
> Add: Enable http2 for GitHub async Client

- pontos/github/api/branch.py
**What**:
Set required checks if it is an empty list
**Why**:
An empty list is a valid and also necessary value.
**How**:
**Checklist**:
> Fix: Set required checks if it is an empty list

- pontos/github/api/branch.py
- pontos/github/api/labels.py
- pontos/github/api/pull_requests.py
- pontos/github/api/release.py
- pontos/github/api/repositories.py
- pontos/github/api/workflows.py
**What**:
Add explicit typing for method that return None
**Why**:
Be explicit about return values.
**How**:
**Checklist**:
> Add: Add explicit typing for methods that return None

- .github/workflows/ci-python.yml
- pontos/github/script/__init__.py
- pyproject.toml
- scripts/github/branchprotection.py
- scripts/github/members.py
- scripts/github/repositories.py
**What**:
First example GitHub scripts.
**Why**:
We want to be able to script all kind of things and these scripts will be a good starting point.
**How**:
**Checklist**:
> GitHub scripts

- pontos/git/git.py
- tests/git/test_git.py
**What**:
Extend the Git class for additional git commands
**Why**:
Allow to call additional git commands via a nice API.
**How**:
**Checklist**:
> Additional git API

- pontos/git/__init__.py
- pontos/github/api/workflows.py
- pontos/pontos.py
- scripts/github/artifacts.py
- scripts/github/create-repository.py
- scripts/github/lock-branch.py
- scripts/github/members.py
- scripts/github/repositories.py
- scripts/github/teams.py
- scripts/github/workflow-runs.py
**What**:
Extend existing scripts:
* members (list members of an org)
* repositories (list repos of an org)
Add new scripts:
* lock-branch (lock/unlock a branch)
* create-repository (create a new repo with our defaults)
* artifacts (list artifacts of a repo)
* teams (list teams of an org)
**Why**:
Improved CLI for GitHub
**How**:
**Checklist**:
> Extend git Scripts

- pontos/github/models/base.py
- pontos/models/__init__.py
- tests/github/models/test_base.py
- tests/models/__init__.py
- tests/models/test_models.py
**What**:
Generalize Model class and make it usable besides GitHub data
**Why**:
Model classes can be used for representing other data like CVE too.
**How**:
**Checklist**:
> Generalize Models

- pontos/terminal/terminal.py
**What**:
Fixed typing issues in terminal.py
**Why**:
To prepare pontos for automatic mypy-checks in the future
**How**:
Fixed occuring errors
`poetry run mypy pontos/terminal/terminal.py`
**Checklist**:
> Typing in terminal.py

- pontos/git/git.py
- tests/git/test_git.py
**What**:
Fixed typing issues in git.py
**Why**:
To prepare pontos for automatic mypy-checks in the future
**How**:
Fixed occuring errors
`poetry run mypy pontos/updateheader/git.py`
**Checklist**:
> Fix: Typing git.py

- pontos/updateheader/updateheader.py
- tests/updateheader/test_header.py
**What**:
Fixed typing issues in updateheader.py
**Why**:
To prepare pontos for automatic mypy-checks in the future
**How**:
Fixed occuring errors
`poetry run mypy pontos/updateheader/updateheader.py`
**Checklist**:
> Typing in updateheader.py

- poetry.lock
- pontos/github/api/__init__.py
- pontos/github/api/api.py
- pontos/github/api/artifacts.py
- pontos/github/api/helper.py
- pontos/github/api/organizations.py
- pontos/github/api/repositories.py
- pontos/github/api/workflows.py
- pontos/github/argparser.py
- pontos/github/models/artifact.py
- pontos/github/models/base.py
- pontos/github/models/branch.py
- pontos/github/models/organization.py
- pontos/github/models/pull_request.py
- pontos/github/models/release.py
- pontos/github/models/workflow.py
- pontos/helper.py
- pontos/models/__init__.py
- pyproject.toml
- scripts/github/repositories.py
- scripts/github/workflow-runs.py
- tests/github/api/test_organizations.py
- tests/github/models/test_artifact.py
- tests/github/models/test_organization.py
- tests/github/models/test_pull_request.py
- tests/github/models/test_release.py
- tests/github/models/test_workflow.py
- tests/models/test_models.py
- tests/test_helper.py
**What**:
* Improve the models by checking the model properties against the GitHub JSON schemas. 
* Put all API related enums into the corresponding model modules.
* Add new enums for enum properties corresponding to the GitHub JSON schemas.
* Use datetime instances instead of str for datetime properties
* Improved type hints.
**Why**:
Cleanup the models to get them right and consistent.
**How**:
**Checklist**:
> Improve GitHub models

- pontos/helper.py
- tests/test_helper.py
**What**:
Add new parse_timedelta function
**Why**:
Allow parsing a timedelta from a string of the following format: `X.YwX.YdX.YhX.YmX.Ys` for example `1.5w1.5d1.5h1.5m1.5s`.
**How**:
Unittests
**Checklist**:
> Add: Add new parse_timedelta function

- .github/PULL_REQUEST_TEMPLATE.md
**What**:
Use an updated PR template
DEVOPS-417
**Why**:
The old template was not well understood and ofter not all sections and checks have been filled. Therefore simplify and reformat the PR template.
> Change: Use an updated PR template

- .github/workflows/release-pontos-manually.yml
- .github/workflows/release-pontos.yml
> Revert "Change: Use release instead of release-python action for deployment"

- .github/workflows/release-pontos-manually.yml
- .github/workflows/release-pontos.yml
Reverts greenbone/pontos#584
Revertception
> Revert "Revert "Change: Use release instead of release-python action for deployment""

- .github/workflows/release-pontos.yml
> Use ref variable in label release

- pontos/version/go.py
- pontos/version/python.py
Also enable using `force` for GoLang Version
Why not. :D
(argument is passed anyways ...)
> Fix: Add functionality of force for go version

- pontos/version/go.py
Dropped PR template / not having added a Fix: in the commit on purpose for such a minor change.
> Fix typo in comment

- pontos/changelog/changelog.py
- pontos/changelog/conventional_commits.py
- pontos/changelog/errors.py
- pontos/release/prepare.py
- tests/changelog/test_conventional_commits.py
Changelog refactor
Cleanup the code
> Changelog refactor

- pontos/helper.py
Drop shell_cmd_runner helper function
The function is not used anymore.
> Remove: Drop shell_cmd_runner helper function

- .github/workflows/release-pontos.yml
Use correct action
Action URL got broken during refactoring
> Fix: Pontos release workflow

- .github/workflows/release-pontos.yml
> Fix: Workflow release file

- .github/workflows/release-pontos.yml
Update release workflow for pontos-release changes
Adjust the release CI workflow to the latest changes in pontos.release.
> Fix release workflow

- .github/workflows/release-pontos.yml
- pontos/release/release.py
Fix release changelog creating via CI workflow
Not all changelog entries have been added to the release changelog because of missing git log messages.
> Fix release

- pontos/release/release.py
- tests/release/test_release.py
Create pre releases on GitHub for pre release release versions. 
Reflect pre releases also on GitHub.
> Change: Also create pre releases on GitHub

- pontos/release/release.py
- pontos/version/helper.py
- tests/version/test_helper.py
Include changes of the previous pre releases in a final release changelog
For a final release we want a full changelog again.
> Release changelog

- pontos/release/release.py
- pontos/version/__init__.py
- pontos/version/commands.py
- pontos/version/project.py
- pontos/version/version.py
- tests/release/test_release.py
- tests/version/test_cmake_version.py
- tests/version/test_commands.py
- tests/version/test_go_version.py
- tests/version/test_javascript_version.py
- tests/version/test_project.py
- tests/version/test_python_version.py
Support projects using several different programming languages.
Allow to increment the version for all programming languages at the same time.
DEVOPS-552
> Multi lanuage projects

- pontos/version/javascript.py
- tests/version/test_javascript_version.py
Besides version in the package.json file now src/version.js and src/version.ts files are considered for reading and writing version information.
Support TypeScript projects for version updates too.
DEVOPS-561
> Add: Support updating a TypeScript version file too

- pontos/release/release.py
Fix: Pass version to string function
Make release already
DEVOPS-598
> Fix: Pass version to string function

- pontos/version/commands/_javascript.py
> Fix javascript by removing semi from regex

- .github/workflows/ci-python.yml
Use poetry 1.4.0 to fix installation of furo sphinx theme for now
It seems poetry 1.4.1 did break the installation of the furo sphinx theme (https://github.com/pradyunsg/furo/discussions/639)
> Use poetry 1.4.0 to fix installation of furo sphinx theme for now

- .github/workflows/ci-python.yml
- .github/workflows/github-pages.yml
- .github/workflows/release-pontos.yml
Fix workflows and enable caching
Missed some workflows where poetry 1.4.0 is required. Also enable caching of python dependencies when using the poetry action.
> Fix workflows and enable caching

- pontos/github/api/tags.py
- pontos/github/models/tag.py
- tests/github/api/test_tags.py
New get_tags GitHub API call to access all repository tags
* Need to access all tags within a repository
DEVOPS-631
> Add: New get_tags GitHub API call

- .github/workflows/ci-python.yml
- .github/workflows/deploy-pypi.yml
- .github/workflows/github-pages.yml
Update CI workflows
* Use newest poetry version
* Cache poetry installation
* Use poetry to upload releases on pypi
Speep up and simplify workflows
> Change: Update CI workflows

- pontos/github/models/base.py
* Add `Event` Enum type `dynamic`
Seems to be an undocumented event type
> Add: `Event` Enum event type `dynamic`

- .github/workflows/deploy-pypi.yml
Fix poetry publish on PyPI
To publish on PyPI :)
> Fix poetry publish on PyPI

- .github/workflows/conventional-commits.yml
Add a workflow for reporting conventional commits
Report conventional commits usage in pull requests
> Add: Add a workflow for reporting conventional commits

- .github/workflows/release-pontos.yml
Fix release action
Use step output for setting the reference and fix release by addressing the enfore-admins script as a module.
https://github.com/greenbone/pontos/actions/runs/5442453024/jobs/9897696051
> Fix release action

- pontos/git/git.py
- tests/git/test_git.py
Extend git class with
* version info
* git log format
* git show implementation
Support more additional git commands
> Extend git

- pontos/release/main.py
- pontos/version/commands/_java.py
- tests/version/commands/test_java.py
Add logging to specific functions
For debugging I need some more information, that can be achieved with logging, best
> Add: Some logging for JavaCmd Class

- pontos/version/commands/_java.py
Log the file content
Can't find problem
DEVOPS-733
> Add: File Content logging warning

- pontos/version/commands/_java.py
Fix: Java Version in swagger regex
regex failed
DEVOPS-733
> Fix: Java Version in swagger regex

- pontos/version/commands/_java.py
Fix: Version Pattern for Java Version Command
It is still not working as expected ...
DEVOPS-733
> Fix: Version Pattern for Java Version Command

- pontos/version/_calculator.py
- tests/version/schemes/test_pep440.py
Support full year (YYYY) for calendar versioning
Required for some of our releases
DEVOPS-733
> Change: Support full year (YYYY) for calendar versioning

- .github/workflows/dependabot-merge.yml
Test auto-merge feature for dependabot
reduce workload
DEVOPS-804
> Add: Test auto-merge feature for dependabot

- .github/workflows/dependabot-merge.yml
Add auto approve
fix auto-merge
for dependabot prs ...
less work for dependabot
devops-804
> Fix: dependabot auto-merge add auto approve

- .github/workflows/dependabot-merge.yml
normal token doesn't work
devops-804
> Fix: Use Greenbone Bot token for dependabot auto-merge

- pontos/version/commands/_java.py
> Change: Use else for logger warning

- .github/dependabot.yml
Group PRs from Dependabot
Less PRs
DEVOPS-804
> Change: Group PRs from Dependabot

- .github/dependabot.yml
Update dependabot.yml's grouping names
Distinguish between actions and python ...
> Update dependabot.yml's grouping names

- .github/workflows/release.yml
Change: Update and rename release-pontos.yml to release.yml
Nameing convention described in DEVOPS-811
DEVOPS-811
> Change: Update and rename release-pontos.yml to release.yml

- .github/workflows/ci-python.yml
- pyproject.toml
Officially support Python 3.12
Python 3.12 got releases just recently and we should support it.
> Add: Officially support Python 3.12

- pontos/github/api/secret_scanning.py
- tests/github/api/test_secret_scanning.py
Improve code examples and add a missing test for the GitHub secret scanning API
Improve the code and code coverage
DEVOPS-817
> Secret scanning Improvements

- pontos/github/api/client.py
- pontos/github/api/code_scanning.py
- pontos/github/models/code_scanning.py
- pontos/version/schemes/_pep440.py
- pontos/version/schemes/_semantic.py
- pontos/version/version.py
- tests/github/api/test_code_scanning.py
- tests/github/models/test_code_scanning.py
Add most important parts of the GitHub code scanning API
Allow to receive and evaluate GitHub code scanning alerts.
DEVOPS-817
> Code scanning API

- pontos/github/scripts/add-topics.py
Add repository topics script
that script can add topics to a list of repositories without overwriting the existing topics 
adding topics to repositories is required for measurements
DEVOPS-831
> Add: Add repository topics script

- pontos/changelog/main.py
- pontos/release/parser.py
Improve CLI help for pontos-changelog and pontos-release
Explain the arguments of ponto-changelog and their purpose. Add descriptions to the pontos-release sub-commands.
> Change: Improve CLI help for pontos-changelog and pontos-release

- pontos/github/scripts/create-repository.py
Cleanup create-repository github script
Move evaluation of input arguments to the top of the code. It's easier to read what's happening if all arguments are evaluated early.
DEVOPS-948
> Change: Cleanup create-repository github script

- pontos/github/actions/core.py
Add a missing ~~quotato~~quote in documentation of actions console
Just accidentally found this issue ...
N/A
> Fix: Missing quotato in documentation of actions console

- .github/workflows/ci-python.yml
Fix: Linting in CI via `ruff check`
`ruff` is deprecated. ...
> Fix: Linting in CI via `ruff check`

- .github/workflows/scorecard.yml
Test Scoreboard on one of our public repositories by adding the workflow
Test Scoreboard
> Add: Test Scoreboard on one of our public repositories

- .github/workflows/auto-merge.yml
- .github/workflows/ci-python.yml
- .github/workflows/codeql-analysis-python.yml
- .github/workflows/deploy-pypi.yml
- .github/workflows/github-pages.yml
- .github/workflows/release.yml
- .github/workflows/sbom-upload.yml
- .github/workflows/scorecard.yml
- .github/workflows/update-header.yml
Worked on some security allerts
[DevOps-1129](https://jira.greenbone.net/browse/DEVOPS-1129)
> Code scanning

- docs/tools.md
- Add `ts` and `tsx` to tools doc
- Forgot to add them in previous PR
> update updateheader docs

- .github/workflows/auto-merge.yml
- .github/workflows/codeql-analysis-python.yml
Fixed typos
[DevOps-1129](https://jira.greenbone.net/browse/DEVOPS-1129)
> fixed typos

- .github/workflows/auto-merge.yml
> Fix: auto-merge
